# QuantumLog 项目代码风格配置
# 基于 Rust 官方推荐的代码风格规范

# 基本格式设置
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# 导入设置
reorder_imports = true
reorder_modules = true
reorder_impl_items = false
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

# 函数和方法格式
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
indent_style = "Block"

# 字符串和注释
format_strings = false
format_macro_matchers = true
format_code_in_doc_comments = false
normalize_comments = false
wrap_comments = false
comment_width = 80

# 结构体和枚举
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# 空格和换行
spaces_around_ranges = false
type_punctuation_density = "Wide"
use_field_init_shorthand = false
force_explicit_abi = true

# 链式调用
chain_width = 60
single_line_if_else_max_width = 50

# 数组和切片
array_width = 60

# 其他设置
remove_nested_parens = true
normalize_doc_attributes = false
license_template_path = ""
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false

# 实验性功能（需要 nightly 版本）
# unstable_features = false
# format_generated_files = true