name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run example basic_usage
      run: cargo test --example basic_usage
    - name: Run example complete_examples
      run: cargo test --example complete_examples
    - name: Run example config_file_example
      run: cargo test --example config_file_example
